version: "2"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: "npm run server"
    volumes:
      - ./server:/home/server
      - server_node_modules:/home/server/node_modules
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: "npm run start"
    ports:
      - "8080:8080" 
    volumes:
      - ./client:/home/client
      - client_node_modules:/home/client/node_modules
  assets:
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
    volumes:
      - ./assets:/www/assets
  haproxy:
    build:
      context: ./services/haproxy
      dockerfile: Dockerfile
    depends_on:
      - server
      - client
      - assets
    ports:
      - "8081:8080"
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - "dev.jmroofing.com"
          - "assets.jmroofing.com"

volumes:
  server_node_modules:
  client_node_modules: